
name: Build Go Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20' # Replace with your Go version

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -o myapp main.go # Replace `myapp` with your desired output binary name

    - name: Archive the build
      uses: actions/upload-artifact@v3
      with:
        name: myapp
        path: myapp
